# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banheiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('banheiros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.Banheiros')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Quartos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='quartos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.Quartos'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.Tipo'),
        ),
        migrations.AddField(
            model_name='item',
            name='transacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.Transacao'),
        ),
        migrations.AddField(
            model_name='item',
            name='vagas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.Vagas'),
        ),
    ]
