# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quartos',
            new_name='Banheiro',
        ),
        migrations.RenameModel(
            old_name='Banheiros',
            new_name='Quarto',
        ),
        migrations.RenameModel(
            old_name='Vagas',
            new_name='Vaga',
        ),
    ]
