# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_auto_20171102_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='banheiro',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quarto',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='transacao',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='nome',
            new_name='name',
        ),
    ]
