# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_auto_20171103_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
